name: Run tests

on: [push, pull_request]

jobs:
  test:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        julia-version: ['1.8', '1.9']
        os: [ubuntu-latest, windows-latest, macOS-latest]
        julia-arch: [x64, x86]
        os: [macOS-latest]
        exclude:
          - os: macOS-latest
            julia-arch: x86

    steps:
      - uses: actions/checkout@v2      
      - uses: julia-actions/setup-julia@v1.9.0
      - uses: julia-actions/julia-buildpkg@v1
      - uses: julia-actions/julia-runtest@v1.8.1
